export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  COMMUNITY_ADMIN = 'COMMUNITY_ADMIN',
  PROVIDER = 'PROVIDER',
  CUSTOMER = 'CUSTOMER',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export enum MarketplaceCategory {
  FOOD = 'FOOD',
  REPAIR = 'REPAIR',
  ELDERLY_CARE = 'ELDERLY_CARE',
  HOME_SERVICES = 'HOME_SERVICES',
  TUTORING = 'TUTORING',
  HANDMADE = 'HANDMADE',
  HEALTH_WELLNESS = 'HEALTH_WELLNESS',
  AGRICULTURE = 'AGRICULTURE',
  FREELANCE = 'FREELANCE',
  COMMUNITY_SHARING = 'COMMUNITY_SHARING',
}

export enum ListingStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING_REVIEW = 'PENDING_REVIEW',
}

export enum MembershipRole {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum NotificationType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_ACCEPTED = 'BOOKING_ACCEPTED',
  BOOKING_REJECTED = 'BOOKING_REJECTED',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PROVIDER_APPROVED = 'PROVIDER_APPROVED',
  PROVIDER_REJECTED = 'PROVIDER_REJECTED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
}

export enum TrialStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  NOT_STARTED = 'NOT_STARTED',
}
