export interface MenuStock { name: string; stock: number; max: number; price: number }

export interface MockListing {
  id: string
  title: string
  description: string
  provider: string
  providerAvatar: string
  providerSince: string
  providerVerified: boolean
  providerTrustScore: number
  providerBio: string
  status: 'available' | 'busy' | 'offline'
  category: string
  price: number
  unit: string
  rating: number
  reviews: number
  community: string
  area: string
  distance: string
  image: string
  tags: string[]
  availableDays: number[]
  openTime: string
  closeTime: string
  responseTime: string
  completedBookings: number
  menuStock?: MenuStock[]
  lat: number
  lng: number
  isPromoted?: boolean
}

export const MOCK_LISTINGS: MockListing[] = [
  {
    id: '1',
    title: 'ทำอาหารกล่องส่งถึงที่',
    description: 'รับทำอาหารกล่องหลากหลายเมนู ทั้งข้าวราดแกง อาหารตามสั่ง ส้มตำ ลาบ ทำจากวัตถุดิบสด ปรุงรสอร่อย สั่งล่วงหน้า 1 วัน จัดส่งถึงบ้านในรัศมี 3 กม. ราคาเหมาะสม รับทั้งแบบรายวันและรายเดือน',
    provider: 'คุณแม่สมใจ', providerAvatar: '👩‍🍳', providerSince: 'ม.ค. 2567',
    providerVerified: true, providerTrustScore: 98,
    providerBio: 'แม่บ้านทำอาหารมา 15 ปี ลูกค้าประจำ 80+ ครัวเรือน รสมือแม่แท้ๆ',
    status: 'available', category: 'FOOD', price: 80, unit: 'กล่อง', isPromoted: true,
    rating: 4.9, reviews: 128, community: 'หมู่บ้านศรีนคร', area: 'บางแค, กรุงเทพฯ',
    distance: '0.3 กม.', image: '🍱', tags: ['ข้าว', 'ส้มตำ', 'ลาบ', 'อาหารตามสั่ง', 'ส่งถึงบ้าน'],
    availableDays: [0,1,2,3,4], openTime: '07:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 342,
    lat: 13.726, lng: 100.482,
    menuStock: [
      { name: 'ข้าวราดแกง', stock: 8, max: 20, price: 80 },
      { name: 'ส้มตำ', stock: 3, max: 15, price: 60 },
      { name: 'ลาบหมู', stock: 0, max: 10, price: 70 },
      { name: 'ต้มยำกุ้ง', stock: 5, max: 8, price: 120 },
    ],
  },
  {
    id: '2',
    title: 'ซ่อมแอร์บ้าน ล้างแอร์',
    description: 'บริการซ่อมและล้างแอร์บ้านทุกยี่ห้อ ช่างมีใบรับรอง ประสบการณ์กว่า 10 ปี ใช้อุปกรณ์มาตรฐาน สามารถออกใบรับประกันงาน 3 เดือน บริการถึงบ้านในเขตกรุงเทพและปริมณฑล',
    provider: 'ช่างสมชาย', providerAvatar: '👨‍🔧', providerSince: 'มี.ค. 2566',
    providerVerified: true, providerTrustScore: 92,
    providerBio: 'ช่างแอร์มืออาชีพ ใบรับรองช่างไฟฟ้า ผลงาน 500+ งาน ไม่ผิดหวัง',
    status: 'busy', category: 'REPAIR', price: 500, unit: 'ครั้ง',
    rating: 4.8, reviews: 87, community: 'หมู่บ้านศรีนคร', area: 'บางแค, กรุงเทพฯ',
    distance: '0.8 กม.', image: '🔧', tags: ['แอร์', 'ซ่อม', 'ล้าง', 'ใบรับประกัน'],
    availableDays: [0,1,2,3,4,5], openTime: '08:00', closeTime: '18:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 215,
    lat: 13.721, lng: 100.487,
  },
  {
    id: '3',
    title: 'สอนภาษาอังกฤษเด็กประถม',
    description: 'สอนภาษาอังกฤษสำหรับเด็กชั้น ป.1–ป.6 เน้นการสนทนา อ่าน เขียน ด้วยเทคนิคที่สนุกและเป็นธรรมชาติ มีประสบการณ์สอนมากกว่า 5 ปี สามารถสอนออนไลน์หรือที่บ้านนักเรียน',
    provider: 'ครูน้องใหม่', providerAvatar: '👩‍🏫', providerSince: 'มิ.ย. 2567',
    providerVerified: true, providerTrustScore: 95,
    providerBio: 'ครูภาษาอังกฤษระดับประถม วุฒิ ป.บัณฑิต ผ่านการอบรม TEFL ลูกศิษย์ 50+ คน',
    status: 'available', category: 'TUTORING', price: 300, unit: 'ชั่วโมง', isPromoted: true,
    rating: 5.0, reviews: 42, community: 'คอนโด The Base', area: 'ลาดพร้าว, กรุงเทพฯ',
    distance: '1.2 กม.', image: '📚', tags: ['ภาษาอังกฤษ', 'ประถม', 'Online', 'สนทนา'],
    availableDays: [1,2,3,4,5,6], openTime: '14:00', closeTime: '20:00',
    responseTime: 'ตอบกลับใน < 30 นาที', completedBookings: 128,
    lat: 13.729, lng: 100.479,
  },
  {
    id: '4',
    title: 'ทำความสะอาดบ้านรายวัน',
    description: 'บริการทำความสะอาดบ้านและคอนโดครบวงจร ทีมงานมืออาชีพ ตรวจสอบประวัติแล้ว ใช้อุปกรณ์และน้ำยาทำความสะอาดมาตรฐาน ISO รับทั้งรายครั้ง รายสัปดาห์ และรายเดือน',
    provider: 'บริษัท Clean Home', providerAvatar: '🧹', providerSince: 'ก.ค. 2565',
    providerVerified: true, providerTrustScore: 96,
    providerBio: 'บริษัทบริการทำความสะอาดมืออาชีพ ทีมงาน 20 คน งาน 5,000+ ครั้ง',
    status: 'available', category: 'HOME_SERVICES', price: 800, unit: 'ครั้ง',
    rating: 4.7, reviews: 203, community: 'คอนโด The Base', area: 'ลาดพร้าว, กรุงเทพฯ',
    distance: '0.5 กม.', image: '🏠', tags: ['บ้าน', 'คอนโด', 'รายวัน', 'ทีมงานมืออาชีพ'],
    availableDays: [0,1,2,3,4,5], openTime: '08:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 1240,
    lat: 13.724, lng: 100.490,
  },
  {
    id: '5',
    title: 'ดูแลผู้สูงอายุกลางวัน',
    description: 'บริการดูแลผู้สูงอายุระหว่างวัน โดยผู้มีประสบการณ์ด้านการดูแลผู้สูงอายุและผู้ป่วย ช่วยทำกิจวัตรประจำวัน กายภาพบำบัดเบื้องต้น พาไปพบแพทย์ ดูแลด้วยความใส่ใจ',
    provider: 'คุณสมศรี', providerAvatar: '👩‍⚕️', providerSince: 'ก.พ. 2568',
    providerVerified: false, providerTrustScore: 75,
    providerBio: 'พยาบาลเกษียณ ประสบการณ์ดูแลผู้สูงอายุ 15 ปี มีใบรับรองการดูแลผู้สูงอายุ',
    status: 'offline', category: 'ELDERLY_CARE', price: 1200, unit: 'วัน',
    rating: 4.9, reviews: 31, community: 'ชุมชนเมืองทอง', area: 'เมืองทอง, นนทบุรี',
    distance: '2.1 กม.', image: '👴', tags: ['ผู้สูงอายุ', 'กลางวัน', 'บ้าน', 'พยาบาล'],
    availableDays: [0,1,2,3,4], openTime: '08:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 3 ชั่วโมง', completedBookings: 67,
    lat: 13.718, lng: 100.483,
  },
  {
    id: '6',
    title: 'กระเป๋าผ้าทอมือ handmade',
    description: 'กระเป๋าผ้าทอมือจากผ้าฝ้ายแท้ 100% งานฝีมือชาวบ้าน ลวดลายไทยเอกลักษณ์ ทนทาน สีสวยไม่ตก มีหลายรูปแบบและขนาด รับออเดอร์ล่วงหน้า 7 วัน สามารถสั่งทำลายพิเศษได้',
    provider: 'ร้านป้าแดง', providerAvatar: '👩‍🎨', providerSince: 'ส.ค. 2566',
    providerVerified: true, providerTrustScore: 88,
    providerBio: 'ช่างฝีมือทอผ้า ประสบการณ์ 20 ปี ลวดลายไทยแท้ ส่งต่างประเทศได้',
    status: 'available', category: 'HANDMADE', price: 350, unit: 'ใบ',
    rating: 4.8, reviews: 56, community: 'เมืองเชียงใหม่ซิตี้', area: 'เมือง, เชียงใหม่',
    distance: '3.4 กม.', image: '🎨', tags: ['กระเป๋า', 'ผ้าทอ', 'Handmade', 'ไทย'],
    availableDays: [0,1,2,3,4,5,6], openTime: '09:00', closeTime: '18:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 180,
    lat: 13.732, lng: 100.476,
    menuStock: [
      { name: 'กระเป๋าสีแดง (M)', stock: 5, max: 10, price: 350 },
      { name: 'กระเป๋าสีน้ำเงิน (M)', stock: 2, max: 8, price: 350 },
      { name: 'กระเป๋าสีเขียว (L)', stock: 3, max: 6, price: 420 },
      { name: 'กระเป๋าออเดอร์พิเศษ', stock: 10, max: 10, price: 550 },
    ],
  },
  {
    id: '7',
    title: 'นวดแผนไทย ออกนอกสถานที่',
    description: 'บริการนวดแผนไทยออกนอกสถานที่ ครูนวดรับรองจากกรมการแพทย์แผนไทย ประสบการณ์กว่า 8 ปี ใช้น้ำมันนวดอย่างดี นวดแก้ปวดเมื่อย คลายกล้ามเนื้อ มีอุปกรณ์ครบ',
    provider: 'หมอนวดประเสริฐ', providerAvatar: '🧘', providerSince: 'พ.ย. 2566',
    providerVerified: true, providerTrustScore: 97,
    providerBio: 'ครูนวดแผนไทยใบรับรองจากกรมการแพทย์ ประสบการณ์ 8 ปี ลูกค้าประจำ 200+ คน',
    status: 'available', category: 'HEALTH_WELLNESS', price: 400, unit: 'ชั่วโมง', isPromoted: true,
    rating: 4.9, reviews: 74, community: 'หมู่บ้านกรีนวิลล์', area: 'บึงกุ่ม, กรุงเทพฯ',
    distance: '1.8 กม.', image: '💆', tags: ['นวด', 'แผนไทย', 'ถึงบ้าน', 'ครูนวดรับรอง'],
    availableDays: [1,2,3,4,5,6], openTime: '10:00', closeTime: '21:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 310,
    lat: 13.715, lng: 100.493,
  },
  {
    id: '8',
    title: 'ผักออร์แกนิคส่งรายสัปดาห์',
    description: 'ผักสวนครัวออร์แกนิค ปลูกเองโดยไม่ใช้สารเคมี ตัดสดทุกเช้า จัดเซ็ตรายสัปดาห์ 5–8 ชนิดหมุนเวียนตามฤดูกาล ส่งถึงบ้านทุกวัน จ อ และ ศ ก่อน 09:00 น. ลองสั่งครั้งแรกฟรีถุงผ้า',
    provider: 'สวนคุณลุงทอง', providerAvatar: '👨‍🌾', providerSince: 'ม.ค. 2567',
    providerVerified: false, providerTrustScore: 80,
    providerBio: 'เกษตรกรออร์แกนิคสวนผัก 2 ไร่ ปลูกมา 6 ปี ผ่านการรับรองจาก Organic Thailand',
    status: 'busy', category: 'AGRICULTURE', price: 250, unit: 'ชุด',
    rating: 4.7, reviews: 38, community: 'ชุมชนริมน้ำ', area: 'ปทุมธานี',
    distance: '4.2 กม.', image: '🌿', tags: ['ผัก', 'ออร์แกนิค', 'ส่งบ้าน', 'ไร้สารเคมี'],
    availableDays: [0,3,6], openTime: '06:00', closeTime: '10:00',
    responseTime: 'ตอบกลับใน < 4 ชั่วโมง', completedBookings: 145,
    lat: 13.737, lng: 100.471,
    menuStock: [
      { name: 'เซ็ตผักใบ (5 ชนิด)', stock: 8, max: 20, price: 250 },
      { name: 'เซ็ตผักผล (5 ชนิด)', stock: 4, max: 15, price: 280 },
      { name: 'เซ็ต Premium (8 ชนิด)', stock: 2, max: 10, price: 420 },
    ],
  },
  {
    id: '9',
    title: 'ออกแบบ Logo & Brand Identity',
    description: 'บริการออกแบบ Logo โลโก้และ Brand Identity ครบวงจร เข้าใจ DNA แบรนด์คุณ ทำ concept หลายแบบให้เลือก แก้ไขไม่จำกัดครั้งจนพอใจ ส่ง source file ครบ ทุก format พร้อมใช้งาน',
    provider: 'ดีไซเนอร์เอ', providerAvatar: '👨‍💻', providerSince: 'ก.ย. 2567',
    providerVerified: true, providerTrustScore: 90,
    providerBio: 'นักออกแบบ Graphic มืออาชีพ ประสบการณ์ 7 ปี ลูกค้าทั่วไทย portfolio 300+ งาน',
    status: 'available', category: 'FREELANCE', price: 3500, unit: 'งาน',
    rating: 4.8, reviews: 19, community: 'คอนโด The Base', area: 'ลาดพร้าว, กรุงเทพฯ',
    distance: '0.9 กม.', image: '💻', tags: ['Logo', 'Design', 'Brand', 'Graphic'],
    availableDays: [0,1,2,3,4], openTime: '09:00', closeTime: '18:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 58,
    lat: 13.722, lng: 100.485,
    menuStock: [
      { name: 'Logo เดี่ยว', stock: 3, max: 5, price: 1500 },
      { name: 'Logo + Stationery', stock: 2, max: 3, price: 3500 },
      { name: 'Full Brand Identity', stock: 1, max: 2, price: 7500 },
    ],
  },
  {
    id: '10',
    title: 'ยืม-คืนอุปกรณ์ทำครัว',
    description: 'แบ่งปันอุปกรณ์ทำครัวในชุมชน เช่น หม้อทอดไร้น้ำมัน เครื่องปั่น ที่ปิ้งย่าง หม้อหุงข้าวขนาดใหญ่ เหมาะสำหรับจัดงาน ปาร์ตี้ ยืมรายวัน ราคาถูก ช่วยลดค่าใช้จ่ายในชุมชน',
    provider: 'Community Pool', providerAvatar: '🤝', providerSince: 'เม.ย. 2568',
    providerVerified: false, providerTrustScore: 72,
    providerBio: 'โครงการ Community Sharing ชุมชนเมืองทอง บริหารโดยคณะกรรมการหมู่บ้าน',
    status: 'available', category: 'COMMUNITY_SHARING', price: 50, unit: 'วัน',
    rating: 4.6, reviews: 22, community: 'ชุมชนเมืองทอง', area: 'เมืองทอง, นนทบุรี',
    distance: '0.7 กม.', image: '🤝', tags: ['ยืม', 'อุปกรณ์', 'แชร์', 'ชุมชน'],
    availableDays: [0,1,2,3,4,5,6], openTime: '08:00', closeTime: '20:00',
    responseTime: 'ตอบกลับใน < 3 ชั่วโมง', completedBookings: 89,
    lat: 13.726, lng: 100.480,
    menuStock: [
      { name: 'หม้อทอดไร้น้ำมัน', stock: 2, max: 3, price: 80 },
      { name: 'เครื่องปั่น', stock: 1, max: 2, price: 50 },
      { name: 'ที่ปิ้งย่างไฟฟ้า', stock: 1, max: 1, price: 100 },
      { name: 'หม้อหุงข้าว 10 ลิตร', stock: 2, max: 2, price: 60 },
    ],
  },
  {
    id: '11',
    title: 'ซ่อมท่อน้ำ-ประปา',
    description: 'บริการซ่อมท่อน้ำ ประปา ก๊อกน้ำรั่ว ท่อแตก ท่ออุดตัน สุขภัณฑ์ ด้วยอุปกรณ์ครบ งานสะอาดเรียบร้อย มีการรับประกันงาน 30 วัน เรียกได้ทุกวัน รวมถึงวันหยุด',
    provider: 'ช่างวิชัย', providerAvatar: '🔧', providerSince: 'ก.พ. 2567',
    providerVerified: true, providerTrustScore: 89,
    providerBio: 'ช่างประปาใบรับรอง ประสบการณ์ 12 ปี ซ่อมได้ทุกปัญหา ราคาตรงไปตรงมา',
    status: 'available', category: 'REPAIR', price: 400, unit: 'ครั้ง',
    rating: 4.6, reviews: 52, community: 'หมู่บ้านศรีนคร', area: 'บางแค, กรุงเทพฯ',
    distance: '0.6 กม.', image: '🔧', tags: ['ท่อน้ำ', 'ประปา', 'ด่วน', 'รับประกัน'],
    availableDays: [0,1,2,3,4,5], openTime: '07:00', closeTime: '19:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 178,
    lat: 13.723, lng: 100.488,
  },
  {
    id: '12',
    title: 'อาหารคลีนออเดอร์ล่วงหน้า',
    description: 'อาหารคลีนเพื่อสุขภาพ คำนวณแคลอรี่ทุกเมนู วัตถุดิบสด ใช้น้ำมันน้อย ไม่มีผงชูรส รองรับอาหารพิเศษ เช่น คีโต ลดน้ำหนัก เบาหวาน สั่งล่วงหน้า 1 วัน ส่งทุกเช้า',
    provider: 'ครัวคลีนคลีน', providerAvatar: '👩‍🍳', providerSince: 'ต.ค. 2567',
    providerVerified: true, providerTrustScore: 94,
    providerBio: 'นักโภชนาการและเชฟอาหารเพื่อสุขภาพ ผ่านการรับรอง Nutrition Certificate',
    status: 'busy', category: 'FOOD', price: 120, unit: 'กล่อง',
    rating: 4.9, reviews: 95, community: 'คอนโด The Base', area: 'ลาดพร้าว, กรุงเทพฯ',
    distance: '1.0 กม.', image: '🥗', tags: ['คลีน', 'ไดเอท', 'รายวัน', 'สุขภาพ'],
    availableDays: [0,1,2,3,4], openTime: '08:00', closeTime: '14:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 267,
    lat: 13.727, lng: 100.483,
    menuStock: [
      { name: 'ไก่อบสมุนไพร', stock: 12, max: 20, price: 120 },
      { name: 'ปลานึ่งมะนาว', stock: 6, max: 15, price: 130 },
      { name: 'สลัดโรลล์', stock: 1, max: 10, price: 100 },
      { name: 'เซ็ตคีโต', stock: 5, max: 8, price: 180 },
    ],
  },
  // ── ภาคเหนือ: เชียงใหม่ ──────────────────────────────────────────────
  {
    id: '13',
    title: 'คลาสทำอาหารเหนือ เชียงใหม่',
    description: 'เรียนทำอาหารเหนือต้นตำรับกับเชฟมืออาชีพ เมนูขึ้นชื่อ: ขนมจีนน้ำเงี้ยว แกงฮังเล ซุปหน่อไม้ และข้าวซอย เรียนเป็นกลุ่มเล็ก สูงสุด 8 คน รวมตลาดเช้า รับวัตถุดิบสด',
    provider: 'เชฟนุ้ย ครัวเหนือ', providerAvatar: '👨‍🍳', providerSince: 'เม.ย. 2567',
    providerVerified: true, providerTrustScore: 91,
    providerBio: 'เชฟอาหารเหนือมืออาชีพ ประสบการณ์ 12 ปี เปิดคลาสนักท่องเที่ยวและคนท้องถิ่น',
    status: 'available', category: 'FOOD', price: 800, unit: 'คน',
    rating: 4.8, reviews: 47, community: 'เมืองเชียงใหม่ซิตี้', area: 'เมือง, เชียงใหม่',
    distance: '2.1 กม.', image: '🫕', tags: ['คลาสทำอาหาร', 'อาหารเหนือ', 'ข้าวซอย', 'เชียงใหม่'],
    availableDays: [0,2,4,6], openTime: '09:00', closeTime: '14:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 156,
    lat: 18.790, lng: 98.993,
    menuStock: [
      { name: 'คลาสเช้า (09:00–12:00)', stock: 4, max: 8, price: 800 },
      { name: 'คลาสบ่าย (13:00–16:00)', stock: 6, max: 8, price: 800 },
      { name: 'คลาส Private (2 คน)', stock: 2, max: 2, price: 1400 },
    ],
  },
  {
    id: '14',
    title: 'สปานวดล้านนา อโรมาเทอราพี',
    description: 'สปาระดับพรีเมียม บรรยากาศล้านนา ใช้สมุนไพรท้องถิ่นเชียงใหม่ ทีมนวดบำบัดผ่านการรับรองนานาชาติ บริการนวดหน้า สปาตัว ล้างผิว และแพ็กเกจคู่ ที่ตั้งย่านนิมมานเฮมิน',
    provider: 'สปาล้านนา', providerAvatar: '🌸', providerSince: 'ก.พ. 2566',
    providerVerified: true, providerTrustScore: 93,
    providerBio: 'สปาระดับพรีเมียม ทีมบำบัดผ่านการรับรองระดับนานาชาติ ใช้สมุนไพรท้องถิ่น',
    status: 'available', category: 'HEALTH_WELLNESS', price: 1200, unit: 'ชั่วโมง', isPromoted: true,
    rating: 4.9, reviews: 112, community: 'นิมมานเฮมิน วิลเลจ', area: 'นิมมานเฮมิน, เชียงใหม่',
    distance: '0.5 กม.', image: '🌺', tags: ['สปา', 'นวด', 'อโรมา', 'นิมมาน', 'เชียงใหม่'],
    availableDays: [0,1,2,3,4,5,6], openTime: '10:00', closeTime: '21:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 420,
    lat: 18.796, lng: 98.968,
    menuStock: [
      { name: 'นวดไทย 60 นาที', stock: 5, max: 6, price: 800 },
      { name: 'อโรมาสปา 90 นาที', stock: 3, max: 4, price: 1200 },
      { name: 'แพ็กเกจคู่ 120 นาที', stock: 2, max: 3, price: 2200 },
    ],
  },
  {
    id: '15',
    title: 'ไกด์เดินป่าดอยสุเทพ',
    description: 'ไกด์เดินป่ามืออาชีพ ใบอนุญาตนำเที่ยว TAT รู้จักพฤกษศาสตร์ สัตว์ป่า และวัฒนธรรมท้องถิ่น เส้นทางดอยสุเทพ น้ำตกมณฑาธาร และหมู่บ้านชาวเขา รวมชุดอุปกรณ์พื้นฐาน',
    provider: 'ไกด์นุ ดอยสุเทพ', providerAvatar: '🏔️', providerSince: 'ก.ย. 2566',
    providerVerified: true, providerTrustScore: 87,
    providerBio: 'ไกด์เดินป่ามืออาชีพ ใบอนุญาตนำเที่ยว ประสบการณ์ 8 ปี ความรู้ธรรมชาติท้องถิ่น',
    status: 'available', category: 'RECREATION', price: 600, unit: 'คน/วัน',
    rating: 4.7, reviews: 63, community: 'เมืองเชียงใหม่ซิตี้', area: 'เมือง, เชียงใหม่',
    distance: '5.2 กม.', image: '⛰️', tags: ['เดินป่า', 'ดอยสุเทพ', 'ธรรมชาติ', 'ไกด์', 'เชียงใหม่'],
    availableDays: [0,2,4,6], openTime: '06:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 215,
    lat: 18.805, lng: 98.922,
  },
  // ── ภาคใต้: ภูเก็ต ──────────────────────────────────────────────────
  {
    id: '16',
    title: 'อาหารทะเลสด ปากน้ำ ภูเก็ต',
    description: 'ร้านอาหารทะเลสดริมทะเลภูเก็ต วัตถุดิบสดจากชาวประมงโดยตรงทุกเช้า ปรุงตามสั่งรสชาติต้นตำรับใต้ บริการนั่งทานในร้าน รับทำกล่องส่ง และจัดเลี้ยงกลุ่ม',
    provider: 'ป้าหนู อาหารทะเล', providerAvatar: '🦞', providerSince: 'ก.พ. 2567',
    providerVerified: true, providerTrustScore: 90,
    providerBio: 'ร้านอาหารทะเลสดริมทะเล วัตถุดิบสดตรงจากชาวประมงทุกวัน รสชาติใต้แท้',
    status: 'available', category: 'FOOD', price: 350, unit: 'จาน',
    rating: 4.8, reviews: 89, community: 'ป่าตอง ซีไซด์', area: 'ป่าตอง, ภูเก็ต',
    distance: '0.4 กม.', image: '🦐', tags: ['อาหารทะเล', 'สด', 'ภูเก็ต', 'ปลา', 'กุ้ง'],
    availableDays: [0,1,2,3,4,5,6], openTime: '10:00', closeTime: '21:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 312,
    lat: 7.880, lng: 98.300,
    menuStock: [
      { name: 'กุ้งเผา (ขีด)', stock: 15, max: 30, price: 350 },
      { name: 'ปลาหมึกย่าง', stock: 8, max: 20, price: 280 },
      { name: 'ปูนึ่ง (ตัว)', stock: 5, max: 10, price: 450 },
      { name: 'ต้มยำทะเล', stock: 10, max: 20, price: 320 },
    ],
  },
  {
    id: '17',
    title: 'เรียนดำน้ำ PADI Open Water ภูเก็ต',
    description: 'คอร์สดำน้ำ PADI Open Water Diver ครบสมบูรณ์ 3-4 วัน ทฤษฎีและปฏิบัติจริง ครูสอน PADI Instructor อุปกรณ์มาตรฐานสากล ปลอดภัย 100% รับ Certificate จริงจาก PADI',
    provider: 'ครูดำน้ำภูเก็ต', providerAvatar: '🤿', providerSince: 'พ.ย. 2565',
    providerVerified: true, providerTrustScore: 95,
    providerBio: 'ครูสอนดำน้ำ PADI Instructor ประสบการณ์ 10 ปี นักเรียน 500+ คน',
    status: 'available', category: 'FITNESS', price: 3500, unit: 'คอร์ส',
    rating: 4.9, reviews: 78, community: 'ป่าตอง ซีไซด์', area: 'ป่าตอง, ภูเก็ต',
    distance: '1.2 กม.', image: '🤿', tags: ['ดำน้ำ', 'PADI', 'Scuba', 'ภูเก็ต', 'Certificate'],
    availableDays: [0,1,2,3,4,5,6], openTime: '07:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 290,
    lat: 7.878, lng: 98.296,
    menuStock: [
      { name: 'Open Water (3 วัน)', stock: 6, max: 8, price: 3500 },
      { name: 'Snorkeling Day Trip', stock: 12, max: 15, price: 1200 },
      { name: 'Advanced Open Water', stock: 3, max: 4, price: 5500 },
    ],
  },
  // ── ภาคอีสาน: ขอนแก่น ───────────────────────────────────────────────
  {
    id: '18',
    title: 'ส้มตำ ลาบ อีสานแท้ ขอนแก่น',
    description: 'ร้านส้มตำอีสานแท้ สูตรลับจากบ้านเกิดขอนแก่น ส้มตำรสจัด ลาบหมูดิบ ลาบสุก ก้อยปลา เมนูขึ้นชื่อ ลูกค้าประจำ 100+ ราย รับส่งออเดอร์ถึงบ้านในเขตเมืองขอนแก่น',
    provider: 'ร้านส้มตำยายแดง', providerAvatar: '🌶️', providerSince: 'ม.ค. 2568',
    providerVerified: true, providerTrustScore: 85,
    providerBio: 'ร้านส้มตำอีสานสูตรต้นตำรับ ประสบการณ์ 10 ปี ลูกค้าประจำ 100+ ราย',
    status: 'available', category: 'FOOD', price: 60, unit: 'จาน',
    rating: 4.7, reviews: 64, community: 'ขอนแก่น อัพทาวน์', area: 'เมือง, ขอนแก่น',
    distance: '1.3 กม.', image: '🥗', tags: ['ส้มตำ', 'ลาบ', 'อีสาน', 'ขอนแก่น', 'เผ็ด'],
    availableDays: [0,1,2,3,4,5,6], openTime: '10:00', closeTime: '20:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 188,
    lat: 16.432, lng: 102.824,
    menuStock: [
      { name: 'ส้มตำไทย', stock: 20, max: 30, price: 60 },
      { name: 'ส้มตำปู', stock: 10, max: 20, price: 70 },
      { name: 'ลาบหมูสุก', stock: 8, max: 15, price: 80 },
      { name: 'ก้อยปลานิล', stock: 5, max: 10, price: 90 },
    ],
  },
  // ── ภาคเหนือ: เชียงใหม่ (ช่าง) ─────────────────────────────────────
  {
    id: '19',
    title: 'ช่างไฟฟ้าบ้าน ติดตั้ง ซ่อม เชียงใหม่',
    description: 'ช่างไฟฟ้าใบอนุญาต กฟน. รับงานทั่วเชียงใหม่ ติดตั้งระบบไฟฟ้าบ้านและคอนโด ซ่อมบอร์ด ปลั๊ก สวิตช์ ระบบแอร์ ติดตั้งโซลาร์เซลล์ รับประกันงาน 1 ปี',
    provider: 'ช่างไฟวิมล', providerAvatar: '⚡', providerSince: 'มิ.ย. 2567',
    providerVerified: true, providerTrustScore: 88,
    providerBio: 'ช่างไฟฟ้าใบอนุญาต กฟน. ประสบการณ์ 9 ปี Solar Certified',
    status: 'busy', category: 'REPAIR', price: 500, unit: 'ครั้ง',
    rating: 4.7, reviews: 41, community: 'เมืองเชียงใหม่ซิตี้', area: 'เมือง, เชียงใหม่',
    distance: '3.0 กม.', image: '⚡', tags: ['ช่างไฟฟ้า', 'ไฟฟ้า', 'โซลาร์', 'เชียงใหม่', 'รับประกัน'],
    availableDays: [0,1,2,3,4,5], openTime: '08:00', closeTime: '18:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 134,
    lat: 18.785, lng: 98.990,
  },
  // ── ปริมณฑล: นนทบุรี ────────────────────────────────────────────────
  {
    id: '20',
    title: 'จัดสวน ดูแลสวนรายเดือน',
    description: 'บริการจัดสวนและดูแลสวนครบวงจร ออกแบบสวน ปลูกต้นไม้ ตัดแต่งกิ่ง ดูแลรายเดือน ใช้ปุ๋ยอินทรีย์ ไม่ใช้ยาฆ่าแมลงอันตราย ทั้งสวนบ้าน คอนโด และสำนักงาน',
    provider: 'สวนสวยบางใหญ่', providerAvatar: '🌳', providerSince: 'ก.ค. 2567',
    providerVerified: true, providerTrustScore: 82,
    providerBio: 'บริการจัดสวนครบวงจร ประสบการณ์ 7 ปี ปุ๋ยอินทรีย์ ไร้สารเคมี',
    status: 'available', category: 'HOME_SERVICES', price: 800, unit: 'ครั้ง',
    rating: 4.6, reviews: 33, community: 'ชุมชนเมืองทอง', area: 'บางใหญ่, นนทบุรี',
    distance: '2.5 กม.', image: '🌳', tags: ['สวน', 'จัดสวน', 'ตัดหญ้า', 'ปุ๋ยอินทรีย์'],
    availableDays: [0,1,2,3,4,5], openTime: '07:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 3 ชั่วโมง', completedBookings: 112,
    lat: 13.848, lng: 100.421,
    menuStock: [
      { name: 'ดูแลรายเดือน (1 ไร่)', stock: 5, max: 8, price: 800 },
      { name: 'ตัดแต่งต้นไม้ (ครั้ง)', stock: 8, max: 10, price: 500 },
      { name: 'ออกแบบสวนใหม่', stock: 2, max: 3, price: 2500 },
    ],
  },
  // ── Phase 13: ชุมชนทั่วประเทศ ────────────────────────────────────────
  {
    id: '21',
    title: 'ก๋วยเตี๋ยวเนื้อ หมู สไตล์นครสวรรค์',
    description: 'ก๋วยเตี๋ยวเนื้อต้มยำสไตล์นครสวรรค์ดั้งเดิม น้ำซุปกระดูกต้มนานกว่า 8 ชั่วโมง เนื้อนุ่มเปื่อย ลูกชิ้นเนื้อทำเอง ราคาคุ้มค่า เปิดบริการทุกวัน ไม่มีวันหยุด',
    provider: 'ร้านก๋วยเตี๋ยวนครสวรรค์', providerAvatar: '🍜', providerSince: 'ต.ค. 2567',
    providerVerified: true, providerTrustScore: 85,
    providerBio: 'สูตรเก่าแก่รุ่นที่ 3 เปิดมา 20 ปี น้ำซุปต้มทุกเช้า เนื้อนุ่มเปื่อย',
    status: 'available', category: 'FOOD', price: 60, unit: 'ชาม',
    rating: 4.7, reviews: 45, community: 'นครสวรรค์ เมือง', area: 'เมือง, นครสวรรค์',
    distance: '0.5 กม.', image: '🍜', tags: ['ก๋วยเตี๋ยว', 'เนื้อ', 'หมู', 'นครสวรรค์', 'ซุปกระดูก'],
    availableDays: [0,1,2,3,4,5,6], openTime: '07:00', closeTime: '15:00',
    responseTime: 'ตอบกลับใน < 30 นาที', completedBookings: 89,
    lat: 15.705, lng: 100.137,
    menuStock: [
      { name: 'ก๋วยเตี๋ยวเนื้อต้มยำ', stock: 30, max: 50, price: 60 },
      { name: 'ก๋วยเตี๋ยวหมูน้ำใส', stock: 25, max: 50, price: 55 },
      { name: 'ก๋วยเตี๋ยวเนื้อแห้ง', stock: 20, max: 40, price: 65 },
    ],
  },
  {
    id: '22',
    title: 'ซ่อมแซมบ้าน ไฟฟ้า ประปา พัทยา',
    description: 'บริการซ่อมแซมครบวงจรในเมืองพัทยาและโดยรอบ ซ่อมแอร์ ประปา ไฟฟ้า กระเบื้อง ทาสี มีช่างหลายทีม รับงานด่วนได้ ราคาโปร่งใส ไม่บวกราคา',
    provider: 'ช่างพัทยา ครบวงจร', providerAvatar: '🔩', providerSince: 'ก.ค. 2567',
    providerVerified: true, providerTrustScore: 87,
    providerBio: 'ทีมช่างพัทยา 5 คน ครอบคลุมทุกงานซ่อมแซม ประสบการณ์รวมกว่า 40 ปี',
    status: 'available', category: 'REPAIR', price: 500, unit: 'งาน',
    rating: 4.6, reviews: 38, community: 'พัทยา บีชซิตี้', area: 'เมืองพัทยา, ชลบุรี',
    distance: '1.0 กม.', image: '🔩', tags: ['ช่าง', 'ซ่อมแซม', 'แอร์', 'ประปา', 'พัทยา'],
    availableDays: [0,1,2,3,4,5,6], openTime: '08:00', closeTime: '20:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 124,
    lat: 12.935, lng: 100.883,
  },
  {
    id: '23',
    title: 'ล่องแก่งแม่น้ำแควน้อย กาญจนบุรี',
    description: 'แพ็กเกจล่องแก่งครึ่งวันและเต็มวัน ครูฝึกมีใบอนุญาต อุปกรณ์ความปลอดภัยครบ ชมวิวธรรมชาติริมแม่น้ำ แคมปิ้ง BBQ ริมน้ำ เหมาะสำหรับครอบครัวและกลุ่มเพื่อน',
    provider: 'ไกด์ล่องแก่งกาญจน์', providerAvatar: '🛶', providerSince: 'ก.ย. 2567',
    providerVerified: true, providerTrustScore: 94,
    providerBio: 'ไกด์ล่องแก่งมืออาชีพ ใบอนุญาตไกด์ท่องเที่ยว ประสบการณ์ 12 ปี',
    status: 'available', category: 'RECREATION', price: 850, unit: 'คน',
    rating: 4.9, reviews: 87, community: 'กาญจนบุรี ริเวอร์', area: 'เมือง, กาญจนบุรี',
    distance: '5.0 กม.', image: '🛶', tags: ['ล่องแก่ง', 'กาญจนบุรี', 'แม่น้ำแคว', 'แคมปิ้ง', 'ธรรมชาติ'],
    availableDays: [4,5,6], openTime: '07:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 203,
    lat: 14.006, lng: 99.548,
    menuStock: [
      { name: 'ล่องแก่งครึ่งวัน (ต่อคน)', stock: 20, max: 30, price: 850 },
      { name: 'ล่องแก่งเต็มวัน + อาหาร', stock: 15, max: 20, price: 1500 },
      { name: 'แคมปิ้ง 2 วัน 1 คืน', stock: 8, max: 12, price: 1800 },
    ],
  },
  {
    id: '24',
    title: 'ดุเรียน เงาะ มังคุด ส่งตรงสวน สุราษฎร์ฯ',
    description: 'ผลไม้สดจากสวนโดยตรง ไม่ผ่านพ่อค้าคนกลาง ดุเรียนหมอนทอง ชะนี เงาะโรงเรียน มังคุด ลองกอง ส่งด่วนทางไปรษณีย์ด้วยกล่องเย็น รับประกันคุณภาพ',
    provider: 'สวนผลไม้สุราษฎร์', providerAvatar: '🍊', providerSince: 'ธ.ค. 2567',
    providerVerified: true, providerTrustScore: 91,
    providerBio: 'เจ้าของสวนผลไม้ 100 ไร่ รุ่นที่ 2 ส่งตรงถึงบ้านทั่วประเทศ',
    status: 'available', category: 'FOOD', price: 290, unit: 'กิโลกรัม',
    rating: 4.8, reviews: 62, community: 'สุราษฎร์ธานี เมือง', area: 'เมือง, สุราษฎร์ธานี',
    distance: '15.0 กม.', image: '🍊', tags: ['ดุเรียน', 'ผลไม้', 'สุราษฎร์', 'ส่งทั่วประเทศ', 'ออร์แกนิค'],
    availableDays: [0,1,2,3,4,5,6], openTime: '06:00', closeTime: '18:00',
    responseTime: 'ตอบกลับใน < 1 ชั่วโมง', completedBookings: 156,
    lat: 9.140, lng: 99.328,
    menuStock: [
      { name: 'ดุเรียนหมอนทอง (กก.)', stock: 200, max: 500, price: 290 },
      { name: 'มังคุด (กก.)', stock: 150, max: 300, price: 120 },
      { name: 'เงาะโรงเรียน (กก.)', stock: 100, max: 200, price: 80 },
    ],
  },
  {
    id: '25',
    title: 'เซรามิคลำปาง สั่งทำตามแบบ',
    description: 'งานเซรามิคฝีมือช่างลำปางรุ่นเก่า ถ้วยชาม แจกัน ของที่ระลึก ของขวัญ สั่งทำตามแบบ พิมพ์ชื่อ โลโก้ได้ ส่งทั่วประเทศ รับประกันคุณภาพ ไม่ผ่านคนกลาง',
    provider: 'เซรามิคลำปาง ช่างบุ', providerAvatar: '🏺', providerSince: 'เม.ย. 2568',
    providerVerified: true, providerTrustScore: 89,
    providerBio: 'ช่างเซรามิคลำปาง รุ่นที่ 3 ประสบการณ์ 25 ปี ส่งออกต่างประเทศ',
    status: 'available', category: 'CRAFT', price: 350, unit: 'ชิ้น',
    rating: 4.9, reviews: 53, community: 'ลำปาง เซรามิค', area: 'เมือง, ลำปาง',
    distance: '2.0 กม.', image: '🏺', tags: ['เซรามิค', 'ลำปาง', 'งานฝีมือ', 'ของขวัญ', 'สั่งทำ'],
    availableDays: [0,1,2,3,4,5], openTime: '08:00', closeTime: '17:00',
    responseTime: 'ตอบกลับใน < 2 ชั่วโมง', completedBookings: 98,
    lat: 18.289, lng: 99.498,
    menuStock: [
      { name: 'ถ้วยชาม Set 6 ใบ', stock: 15, max: 30, price: 480 },
      { name: 'แจกันลายไทย (ชิ้น)', stock: 10, max: 20, price: 650 },
      { name: 'ของที่ระลึกสั่งทำ', stock: 20, max: 50, price: 350 },
    ],
  },
]

export function getListingById(id: string): MockListing | undefined {
  return MOCK_LISTINGS.find(l => l.id === id)
}
